---

- name: Check network device OS
  assert:
    that: >
      ansible_network_os == 'nxos' or
      ansible_network_os == 'ios'
    msg: "Network device OS not defined or not supported by this role: {{ ansible_network_os }}"

- name: Add/remove nxos vrfs
  nxos_vrf:    
      name: "{{ item.value.name }}"    
      description:  "{{ item.value.description | default(omit) }}" 
      state: "{{ item.value.state | default('present') }}"
      admin_state: "{{ item.value.admin_state | default('up') }}"
      delay: "{{ item.value.delay | default(omit) }}"
      rd: "{{ item.value.rd | default(omit) }}"
  loop: "{{ vrfs | dict2items }}"    
  when: >
    ansible_network_os == 'nxos' and
    vrfs is defined 
  tags: 
    - vrf_config
    - nxos


